/**********************************************************
S-MOS SED1520 Graphic LCD controller demo
(C) Copyright 2011 Pavel Haiduc, HP InfoTech s.r.l.
http://www.hpinfotech.com

The program is designed to be compiled with the Evaluation
version, so it's capabilities are limited.

The demo is designed to run on any ATmega128A
development board with chip clock of 16 MHz.

The 122x32 graphic LCD module connections are:
DB0    - PORTA bit 0
DB1    - PORTA bit 1
DB2    - PORTA bit 2
DB3    - PORTA bit 3
DB4    - PORTA bit 4
DB5    - PORTA bit 5
DB6    - PORTA bit 6
DB7    - PORTA bit 7

RD/WR  - PORTC bit 1
A0     - PORTC bit 2
/RES   - PORTC bit 3
E1     - PORTC bit 4
E2     - PORTC bit 5

CL     - PORTB bit 4 (if needed)

Some displays require an external 2kHz clock signal CL.
This signal, generated by ATmega128A Timer/Counter 0,
will be available on PORTB bit 4.

Important Note: There are two kinds of 122x32
pixels SED1520 LCD modules.
Some of them have active high Enable signals
(E1, E2) and single RD/WR signal,
while others have active low Chip Select signals
(/CS1, /CS2) and separate /RD and /WR signals.
Make sure to specify the correct connections in the
Project|Configure|C Compiler|Libraries|Graphic LCD menu.

The LCD module contrast control voltage must be supplied
as specified in it's datasheet.
**********************************************************/

#include <io.h>
#include <glcd.h>
#include <delay.h>

void main()
{
GLCDINIT_t init;

/* Set PORTB bit 4 (OC0) as output for display clock signal */
DDRB.4=1;

/* Timer/Counter 0 initialization
   Clock source: System Clock
   Clock value: 15.625 kHz
   Mode: CTC top=OCR0
   OC0 output: Toggle on compare match */
ASSR=0x00;
TCCR0=0x1F;
OCR0=0x03;

/* No font is used */
init.font=NULL;
 
/* No need for reading data from external memory */
init.readxmem=NULL;

/* No need for reading data from external memory */ 
init.writexmem=NULL;

/* Initialize the LCD controller and graphics */
glcd_init(&init); 

/* Draw various styles of lines */
/* Line thickness: 1 pixel */
glcd_line(0,0,121,0);

glcd_setlinestyle(1,GLCD_LINE_DOT_SMALL);
glcd_line(0,2,121,2);

glcd_setlinestyle(1,GLCD_LINE_DOT_LARGE);
glcd_line(0,4,121,4);

/* Line thickness: 2 pixels */
glcd_setlinestyle(2,GLCD_LINE_SOLID);
glcd_line(0,6,121,6);

glcd_setlinestyle(2,GLCD_LINE_DOT_SMALL);
glcd_line(0,10,121,10);

glcd_setlinestyle(2,GLCD_LINE_DOT_LARGE);
glcd_line(0,14,121,14);

/* Line thickness: 4 pixels */
glcd_setlinestyle(4,GLCD_LINE_SOLID);
glcd_line(0,18,121,18);

glcd_setlinestyle(4,GLCD_LINE_DOT_LARGE);
glcd_line(0,24,121,24);

/* 4 seconds delay */
delay_ms(4000);

/* Clear display */
glcd_clear();

/* Line thickness: 2 pixels */
glcd_setlinestyle(2,GLCD_LINE_SOLID);

/* Draw a rounded rectangle */
glcd_rectround(0,0,121,15,5);

/* Dotted line thickness: 2 pixels */
glcd_setlinestyle(2,GLCD_LINE_DOT_SMALL);

/* Draw a rectangle */
glcd_rectrel(0,16,121,15);
}
