/**********************************************************************
Solomon Systech SSD1306 Graphic controller demo
(C) Copyright 2011-2015 Pavel Haiduc, HP InfoTech s.r.l.
http://www.hpinfotech.com

The demo is designed to run on an ATxmega128A1
XMEGA-A1 Xplained development board with chip clock of 2 MHz.

A module with the Univision UG-2864HSWEG01 128x64 OLED display
was used for the purpose of this demo.
It can be purchased from:
http://www.wide.hk/products.php?product=0.96%22-128x64-OLED-Display-Module-SSD1306

The display module connections are:
DB0    - PORTA bit 0
DB1    - PORTA bit 1
DB2    - PORTA bit 2
DB3    - PORTA bit 3
DB4    - PORTA bit 4
DB5    - PORTA bit 5
DB6    - PORTA bit 6
DB7    - PORTA bit 7

RS     - PORTD bit 0
/CS    - PORTD bit 1
/WR    - PORTD bit 2
/RD    - PORTD bit 3
/RES   - PORTD bit 4

VIN    - not connected, 
         the Vcc voltage is generated by the internal DC/DC converter
3V3    - +3.3V from power supply
GND    - GND

Make sure to specify the correct connections in the
Project|Configure|C Compiler|Libraries|Graphic LCD menu.
**********************************************************************/

#include <io.h>
#include <glcd.h>
#include <delay.h>

void main()
{
int x;
GLCDINIT_t init;


/* no font is used */
init.font=NULL;

/* No need for reading data from external memory */
init.readxmem=NULL;

/* No need for reading data from external memory */
init.writexmem=NULL;

/* Set horizontal scan direction for Univision UG-2864HSWEG01: reversed */
init.reverse_x=SSD1306_REVX_REV;

/* Set vertical scan direction for Univision UG-2864HSWEG01: reversed */
init.reverse_y=SSD1306_REVY_REV;

/* Set value for COM outputs configuration
   for Univision UG-2864HSWEG01: interlaced */
init.interlaced=SSD1306_INTERLACED;

/* The Vcc voltage is generated by the internal DC/DC converter */
init.external_vcc=SSD1306_USE_INTERNAL_DCDC;

/* Set contrast */
init.contrast=SSD1306_DEFAULT_CONTRAST;

/* Initialize the LCD controller and graphics */
glcd_init(&init);

/* Draw some lines */
for (x=0; x<80; x+=4) glcd_line(0,0,x,63);
for (x=79; x>=0; x-=4) glcd_line(79,63,x,0);

/* Draw various styles of lines */
/* Line thickness: 1 pixel */
glcd_line(85,10,127,10);

glcd_setlinestyle(1,GLCD_LINE_DOT_SMALL);
glcd_line(85,15,127,15);

glcd_setlinestyle(1,GLCD_LINE_DOT_LARGE);
glcd_line(85,20,127,20);

/* Line thickness: 2 pixels */
glcd_setlinestyle(2,GLCD_LINE_SOLID);
glcd_line(85,25,127,25);

glcd_setlinestyle(2,GLCD_LINE_DOT_SMALL);
glcd_line(85,30,127,30);

glcd_setlinestyle(2,GLCD_LINE_DOT_LARGE);
glcd_line(85,35,127,35);

/* Line thickness: 4 pixels */
glcd_setlinestyle(4,GLCD_LINE_SOLID);
glcd_line(85,40,127,40);

glcd_setlinestyle(4,GLCD_LINE_DOT_SMALL);
glcd_line(85,45,127,45);

glcd_setlinestyle(4,GLCD_LINE_DOT_LARGE);
glcd_line(85,50,127,50);

/* 4 seconds delay */
delay_ms(4000);

/* Clear display */
glcd_clear();

/* Draw a circle with line thickness: 1 pixel */
glcd_setlinestyle(1,GLCD_LINE_SOLID);
glcd_circle(63,31,30);

/* Draw a circle with line thickness: 4 pixels */
glcd_setlinestyle(4,GLCD_LINE_SOLID);
glcd_circle(63,31,25);
}
