/**********************************************************
Font generated by the LCD Vision V1.00 font editor
(C) Copyright 2011 Pavel Haiduc, HP InfoTech s.r.l.
http://www.hpinfotech.com

Font name: font5x7
Fixed font width: 5 pixels
Font height: 7 pixels
First character: 0x20
Last character: 0x7F
**********************************************************/

#ifndef _FONT5X7_INCLUDED_
#define _FONT5X7_INCLUDED_

extern flash unsigned char font5x7[];

#pragma library font5x7.lib

#endif

