extern flash char http_http[8];
extern flash char http_200[5];
extern flash char http_301[5];
extern flash char http_302[5];
extern flash char http_get[5];
extern flash char http_10[9];
extern flash char http_11[9];
extern flash char http_content_type[15];
extern flash char http_texthtml[10];
extern flash char http_location[11];
extern flash char http_host[7];
extern flash char http_crnl[3];
extern flash char http_index_html[12];
extern flash char http_404_html[10];
extern flash char http_referer[9];
extern flash char http_header_200[84];
extern flash char http_header_404[91];
extern flash char http_content_type_plain[29];
extern flash char http_content_type_html[28];
extern flash char http_content_type_css [27];
extern flash char http_content_type_text[28];
extern flash char http_content_type_png [28];
extern flash char http_content_type_gif [28];
extern flash char http_content_type_jpg [29];
extern flash char http_content_type_binary[43];
extern flash char http_html[6];
extern flash char http_shtml[7];
extern flash char http_htm[5];
extern flash char http_css[5];
extern flash char http_png[5];
extern flash char http_gif[5];
extern flash char http_jpg[5];
extern flash char http_text[5];
extern flash char http_txt[5];
