/* definitions generated by preprocessor, copy into defines.h */		
#ifndef	PPINC	
#define	_ATMEGA128	// device select: _ATMEGAxxxx
#define	_B2048	// boot size select: _Bxxxx (words), powers of two only
#include	<io.h>	

/* define pin for enter-self-prog-mode */		
#define	PROGPORT	PORTD
#define	PROGPIN	PIND
#define	PROG_NO	4 // PD4

/* baud rate register value calculation */		
#define	CPU_FREQ	_MCU_CLOCK_FREQUENCY_
#define	BAUD_RATE	115200
#define	BRREG_VALUE	1

/* definitions for UART control */		
#define	BAUD_RATE_LOW_REG	UBRR0L
#define	UART_CONTROL_REG	UCSR0B
#define	ENABLE_TRANSMITTER_BIT	TXEN0
#define	ENABLE_RECEIVER_BIT	RXEN0
#define	UART_STATUS_REG	UCSR0A
#define	TRANSMIT_COMPLETE_BIT	TXC0
#define	RECEIVE_COMPLETE_BIT	RXC0
#define	UART_DATA_REG	UDR0

/* definitions for SPM control */		
#define	SPMCR_REG	SPMCSR
#asm
     #define WR_SPMCR_REG_R22 sts 0x68,r22
#endasm

#define	PAGESIZE	256
#define	APP_END	126976
#define	LARGE_MEMORY	

/* definitions for device recognition */		
#define	PARTCODE	0x44
#define	SIGNATURE_BYTE_1	0x1E
#define	SIGNATURE_BYTE_2	0x97
#define	SIGNATURE_BYTE_3	0x02

/* indicate that preprocessor result is included */		
#define	PPINC	
#endif		
